### ISSUE TITLE
Make a creative Nav bar

### ISSUE THREAD

**Issue by deepeshmlgupta** [Bookingjini-Labs/bookingjini-icons#152]
Why do you want to add this feature?
Creating an attractive nav bar makes the user to remember the website

**Describe the solution you'd like**
I can add a creative nav bar for your website

Please assign this issue to me under GSSOC'23

**Comment by purnima143** [comment]
@deepeshgupta3257 Could you please provide more details about what you intend to include in the navbar?

**Comment by Pv200** [comment]
Hey purnima143,
This issue  is all about the logo, logotext, download button, cnd button are not aligned properly due to which the website getting bit unattractive,
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/117562053/26b4c69b-6212-4319-a3d3-23e49d868852)
this what i am talking about, so please assign me this issue under gssoc'23

**Comment by Pv200** [comment]
I will add a navbar and adjust the padding and margin of navigation bar so that it will look more attractive  and also adjust the background color of  nav bar according to darkmode and light mode. 
after doing all these changes it will look like this:
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/117562053/290b8464-4322-4fee-a687-26266feb7a2e)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/117562053/8f1014c7-a435-44ad-8f54-b20402b1e79a)
so please assignme this issue under gssoc'23
