### ISSUE TITLE
Making the Website Responsive 

### ISSUE THREAD

**Issue by rt-001** [Bookingjini-Labs/bookingjini-icons#33]
I would like to work on this issue

**Current UI**
<img width="1440" alt="Screenshot 2023-05-20 at 1 49 05 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/76102333/b1926c38-bd36-4b9a-95b7-8fe693267d8f">

**Comment by ARGHYADIPROY** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly assign me the issue.@Bookingjini-Labs

I will make this website responsive in all modes. Please assign me this issue.

**Comment by premsaivarmachekuri** [comment]
Hi @bookingjini ,

I am writing to express my interest in contributing to the project and to request assignment of the issue "Making the Website Responsive."

As a participant in GSSoC'23, I have been looking for an engaging project that aligns with my skills, and this particular issue seems to be a perfect fit. I have experience in web development and have successfully worked on similar tasks in the past.

By making the website responsive in all modes using media queries and effective CSS techniques, we can ensure an optimal user experience across various devices and screen sizes. I will carefully craft the responsive design, considering factors such as layout adjustments, font sizes, image scaling, and navigation optimization.

This improvement will greatly enhance the accessibility and usability of the website for all users, regardless of the device they are accessing it from.

I kindly request you to assign me this issue so that I can start working on it promptly. I am excited about the opportunity to contribute to the project and look forward to collaborating with the team.

Thank you for your time and consideration. I am eager to begin working on this task and make a positive impact on the project.

Best regards,
Premsai Varma

**Comment by AshutoshDash1999** [comment]
Duplicate issue #22
